import { IconType } from "react-icons";

import {
  HiChevronUp,
  HiChevronDown,
  HiChevronRight,
  HiChevronLeft,
  HiArrowUpRight,
  HiOutlineArrowPath,
  HiCheck,
  HiMiniQuestionMarkCircle,
  HiMiniXMark,
  HiOutlineLink,
  HiExclamationTriangle,
  HiInformationCircle,
  HiExclamationCircle,
  HiCheckCircle,
  HiMiniGlobeAsiaAustralia,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiClipboard,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiMoon,
  HiSun,
  HiOutlineDocument,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiTypescript,
  SiReact,
  SiRedux,
  SiNextdotjs,
  SiTailwindcss,
  SiChakraui,
  SiCypress,
  SiJest,
  SiNodedotjs,
  SiExpress,
  SiGraphql,
  SiPython,
  SiDjango,
  SiFastapi,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiTensorflow,
  SiDocker,
  SiKubernetes,
  SiGit,
  SiVuedotjs,
  SiSpringboot,
  SiPhp,
  SiLaravel,
  SiGooglecloud
} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaTelegram } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  chevronUp: HiChevronUp,
  chevronDown: HiChevronDown,
  chevronRight: HiChevronRight,
  chevronLeft: HiChevronLeft,
  refresh: HiOutlineArrowPath,
  arrowUpRight: HiArrowUpRight,
  check: HiCheck,
  arrowRight: HiArrowRight,
  helpCircle: HiMiniQuestionMarkCircle,
  infoCircle: HiInformationCircle,
  warningTriangle: HiExclamationTriangle,
  errorCircle: HiExclamationCircle,
  checkCircle: HiCheckCircle,
  email: HiEnvelope,
  globe: HiMiniGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  close: HiMiniXMark,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  telegram: FaTelegram,
  x: FaX,
  clipboard: HiClipboard,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  moon: HiMoon,
  sun: HiSun,
  document: HiOutlineDocument,
  javascript: SiJavascript,
  typescript: SiTypescript,
  react: SiReact,
  vue: SiVuedotjs,
  redux: SiRedux,
  nextjs: SiNextdotjs,
  tailwind: SiTailwindcss,
  chakraui: SiChakraui,
  cypress: SiCypress,
  jest: SiJest,
  nodejs: SiNodedotjs,
  express: SiExpress,
  graphql: SiGraphql,
  python: SiPython,
  django: SiDjango,
  fastapi: SiFastapi,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  mongodb: SiMongodb,
  redis: SiRedis,
  tensorflow: SiTensorflow,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  git: SiGit,
  springboot: SiSpringboot,
  gcp:SiGooglecloud,
  php:SiPhp,
  laravel:SiLaravel,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
