import { IconType } from "react-icons";

import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiReact,
  SiNextdotjs,
  SiReactos,
  SiAngular,
  SiRedux,
  SiSolidity,
  SiRust,
  SiWeb3Dotjs,
  SiWagmi,
  SiWalletconnect,
  SiTailwindcss,
  SiGraphql,
  SiNodedotjs,
  SiExpress,
  SiDjango,
  SiFastapi,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiRedis,
  SiJson,
  SiCypress,
  SiJest,
  SiDocker,
  SiCircleci,
  SiKubernetes,
  SiGithub,
  SiEthers,
} from "react-icons/si";

import {
  HiChevronUp,
  HiChevronDown,
  HiChevronRight,
  HiChevronLeft,
  HiArrowUpRight,
  HiOutlineArrowPath,
  HiCheck,
  HiMiniQuestionMarkCircle,
  HiMiniXMark,
  HiOutlineLink,
  HiExclamationTriangle,
  HiInformationCircle,
  HiExclamationCircle,
  HiCheckCircle,
  HiMiniGlobeAsiaAustralia,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiClipboard,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaXTwitter,
  FaTelegram,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  chevronUp: HiChevronUp,
  chevronDown: HiChevronDown,
  chevronRight: HiChevronRight,
  chevronLeft: HiChevronLeft,
  refresh: HiOutlineArrowPath,
  arrowUpRight: HiArrowUpRight,
  check: HiCheck,
  arrowRight: HiArrowRight,
  helpCircle: HiMiniQuestionMarkCircle,
  infoCircle: HiInformationCircle,
  warningTriangle: HiExclamationTriangle,
  errorCircle: HiExclamationCircle,
  checkCircle: HiCheckCircle,
  email: HiEnvelope,
  globe: HiMiniGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  close: HiMiniXMark,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  telegram: FaTelegram,
  javascript: SiJavascript,
  typescript: SiTypescript,
  python: SiPython,
  react: SiReact,
  nextjs: SiNextdotjs,
  reactnative: SiReactos,      // placeholder since no dedicated React Native icon in react-icons/si
  angularjs: SiAngular,
  redux: SiRedux,
  solidity: SiSolidity,
  rust: SiRust,
  web3js: SiWeb3Dotjs,
  wagmi: SiWagmi,
  walletconnect: SiWalletconnect,
  tailwindcss: SiTailwindcss,
  graphql: SiGraphql,
  nodejs: SiNodedotjs,
  express: SiExpress,
  django: SiDjango,
  fastapi: SiFastapi,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  mongodb: SiMongodb,
  redis: SiRedis,
  json: SiJson,
  cypress: SiCypress,
  jest: SiJest,
  ethers:SiEthers,
  docker: SiDocker,
  cicd: SiCircleci,
  kubernetes: SiKubernetes,
  githubIcon: SiGithub,
  x: FaXTwitter,
  clipboard: HiClipboard,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
};
